#!/bin/bash

echo "Running git pre-commit hook"

./gradlew ktlint

#./gradlew sonarqube -D "sonar.host.url=http://69.69.69.56:9000/" -D "sonar.login=6fb2eb206edf69c629e0a7ce79b1b34d27d52198"
#./gradlew clean connectedAndroidTest test createDebugCoverageReport sonarqube

RESULT=$?

if [ "$RESULT" = 0 ] ; then
    echo "Static analysis found no problems."
    exit 0
else
    echo 1>&2 "Static analysis found violations it could not fix."
    exit 1
fi